name: Build Release Artifacts
on:
  release:
    types: [created]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk+fx'

      - run: ./gradlew check packageImage

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/logfx-1.0-RC4.zip
          asset_name: logfx-1.0-RC4.zip
          asset_content_type: application/zip
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk+fx'

      - run: ./gradlew packageImage

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/logfx-1.0-RC4.zip
          asset_name: logfx-1.0-RC4.zip
          asset_content_type: application/zip
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk+fx'

      - run: ./gradlew check packageImage

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/logfx-1.0-RC4.zip
          asset_name: logfx-1.0-RC4.zip
          asset_content_type: application/zip
