name: Build Release Artifacts
on:
  release:
    types: [created, edited]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk+fx'

      - name: Package Java Image
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: ./gradlew check packageImage

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/logfx-${{ github.ref }}.zip
          asset_name: logfx-${{ github.ref }}-linux.zip
          asset_content_type: application/zip
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk+fx'

      - name: Package Java Image
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: ./gradlew packageImage

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/logfx-${{ github.ref }}.zip
          asset_name: logfx-${{ github.ref }}-macos.zip
          asset_content_type: application/zip
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk+fx'

      - name: Package Java Image
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: ./gradlew check packageImage

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/logfx-${{ github.ref }}-windows.zip
          asset_name: logfx-${{ github.ref }}.zip
          asset_content_type: application/zip
